--- 4.1

-- a

-- 

SELECT MANAGER_ID, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL GROUP BY MANAGER_ID;

-- b

SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT FROM EMPLOYEES WHERE SALARY > 30000 GROUP BY DEPARTMENT_ID;

-- advanced query below

SELECT D.DEPARTMENT_ID, COUNT(*) EMPLOYEE_COUNT FROM DEPARTMENTS D JOIN EMPLOYEES E ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID) WHERE E.SALARY>30000 GROUP BY D.DEPARTMENT_ID;

-- c

SELECT DEPARTMENT_ID, MAX(SALARY) MAX_SAL,MIN(SALARY) MIN_SAL, AVG(SALARY) AVG_SAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY AVG_SAL DESC, MAX_SAL DESC, MIN_SAL DESC;

-- advanced query below
 
SELECT D.DEPARTMENT_ID, MAX(E.SALARY) MAX_SAL, MIN(E.SALARY) MIN_SAL, AVG(E.SALARY) AVG_SAL FROM DEPARTMENTS D JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID GROUP BY D.DEPARTMENT_ID ORDER BY AVG_SAL DESC, MAX_SAL DESC, MIN_SAL DESC;

--- 4.2

-- a

SELECT DEPARTMENT_ID, AVG(SALARY) AVG_SAL FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) <= 50000;

-- advanced query below

SELECT D.DEPARTMENT_ID, AVG(E.SALARY) AVG_SAL FROM DEPARTMENTS D JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID GROUP BY D.DEPARTMENT_ID HAVING AVG(E.SALARY) <= 50000;

--- 4.3

-- a

SELECT FLOOR(SALARY/5000) SALARY_GROUP, COUNT(*) FROM EMPLOYEES GROUP BY FLOOR(SALARY/5000) ORDER BY SALARY_GROUP ASC;

-- b

SELECT TO_CHAR(HIRE_DATE, 'YYYY') YEAR, JOB_ID, COUNT(*) EMPLOYEES_HIRED FROM EMPLOYEES GROUP BY TO_CHAR(HIRE_DATE, 'YYYY'), JOB_ID ORDER BY YEAR ASC, JOB_ID ASC;



