--- 11.3

-- a

SELECT
  (CASE WHEN SALARY < 5000 THEN 'C' WHEN SALARY < 10000 THEN 'B' WHEN SALARY < 15000 THEN 'A' ELSE 'A+' END) "SALARY GRADE",
  COUNT(*)
FROM
  EMPLOYEES
GROUP BY
  (CASE WHEN SALARY < 5000 THEN 'C' WHEN SALARY < 10000 THEN 'B' WHEN SALARY < 15000 THEN 'A' ELSE 'A+' END)
ORDER BY
  "SALARY GRADE" ASC

-- b

SELECT
  DECODE(TRUNC(SALARY / 5000), 0, 'C', 1, 'B', 2, 'A', 'A+') AS "SALARY GRADE",
  COUNT(*) AS EMPLOYEE_COUNT
FROM
  EMPLOYEES
GROUP BY
  DECODE(TRUNC(SALARY / 5000), 0, 'C', 1, 'B', 2, 'A', 'A+')
ORDER BY
  "SALARY GRADE";

-- c

SELECT
  E.EMPLOYEE_ID,
  E.LAST_NAME,
  E.DEPARTMENT_ID,
  E.MANAGER_ID,
  D.DEPT_COUNT AS EMP_DEPT_COUNT,
  MGR_DEPT.DEPT_COUNT AS MANAGER_DEPT_COUNT
FROM
  EMPLOYEES E
  LEFT JOIN (SELECT DEPARTMENT_ID, COUNT(*) AS DEPT_COUNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID) D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT JOIN (
    SELECT
      M.EMPLOYEE_ID AS MANAGER_ID,
      COUNT(*) AS DEPT_COUNT
    FROM
      EMPLOYEES E2
      JOIN EMPLOYEES M ON E2.DEPARTMENT_ID = M.DEPARTMENT_ID
    GROUP BY
      M.EMPLOYEE_ID
  ) MGR_DEPT ON E.MANAGER_ID = MGR_DEPT.MANAGER_ID;

