--- 3.1

-- a

SELECT UPPER(SUBSTR(COUNTRY_NAME,1,3)) AS FIRST_THREE, UPPER(SUBSTR(COUNTRY_NAME,LENGTH(COUNTRY_NAME)-2,3)) AS LAST_THREE FROM COUNTRIES;

-- b

SELECT LPAD(FIRST_NAME || ' ' || LAST_NAME,60,'*') AS NAME FROM EMPLOYEES;

-- c

SELECT DISTINCT JOB_TITLE FROM JOBS WHERE LOWER(JOB_TITLE) LIKE '%manager%'; 

--- 3.2

-- a

SELECT LAST_NAME, ROUND((SYSDATE-HIRE_DATE),2) DAYS_EMPLOYED FROM EMPLOYEES;

-- b

SELECT LAST_NAME, ROUND((SYSDATE-HIRE_DATE)/365,2) YEARS_EMPLOYED FROM EMPLOYEES;

--- 3.3

-- a

SELECT FIRST_NAME, ROUND((SYSDATE-HIRE_DATE)/365,2) YEARS_EMPLOYED FROM EMPLOYEES;

-- b

SELECT LAST_NAME, (LAST_DAY(HIRE_DATE)-HIRE_DATE) DAYS_IN_FIRST_MONTH FROM EMPLOYEES;

--- 3.4

-- a

SELECT COMMISSION_PCT FROM EMPLOYEES WHERE NVL(COMMISSION_PCT,0)>=.2;

-- b

SELECT LAST_NAME, NVL(66*SALARY,0) FROM EMPLOYEES;

--- 3.5

-- a.i

SELECT TO_CHAR(HIRE_DATE,'DDth Month,YYYY') "HIRE DATE" FROM EMPLOYEES;

-- a.ii

SELECT TO_CHAR(HIRE_DATE,'DD Month,YYYY') "HIRE DATE" FROM EMPLOYEES;