--- 7.1

-- a

SELECT EMPLOYEE_ID FROM EMPLOYEES MINUS ( SELECT EMPLOYEE_ID FROM EMPLOYEES E WHERE EXISTS (SELECT * FROM EMPLOYEES WHERE MANAGER_ID = E.EMPLOYEE_ID));

-- b

SELECT LAST_NAME FROM EMPLOYEES MINUS ( SELECT LAST_NAME FROM EMPLOYEES E WHERE EXISTS (SELECT * FROM EMPLOYEES WHERE MANAGER_ID = E.EMPLOYEE_ID));

-- c

SELECT LOCATION_ID FROM LOCATIONS MINUS (SELECT LOCATION_ID FROM LOCATIONS L WHERE EXISTS(SELECT 1 FROM DEPARTMENTS WHERE LOCATION_ID = L.LOCATION_ID));