--- 5

-- a

SELECT LAST_NAME, SALARY, J.JOB_TITLE FROM EMPLOYEES E JOIN JOBS J ON (E.JOB_ID = J.JOB_ID);

-- b

SELECT D.DEPARTMENT_NAME, C.COUNTRY_NAME FROM DEPARTMENTS D JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID) JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID);

-- c

SELECT C.COUNTRY_NAME, COUNT(*) DEPT_COUNT FROM COUNTRIES C JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID JOIN DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID GROUP BY C.COUNTRY_NAME;

-- d

SELECT LAST_NAME, COUNT(*) JOB_SWITCH_COUNT FROM EMPLOYEES E JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID GROUP BY LAST_NAME;

-- e

SELECT D.DEPARTMENT_NAME, J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) FROM DEPARTMENTS D JOIN EMPLOYEES E  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID JOIN JOBS J ON E.JOB_ID = J.JOB_ID GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE;

-- f

SELECT E.EMPLOYEE_ID, COUNT(E2.EMPLOYEE_ID) EMPLOYEES_HIRED_BEFORE FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON E.HIRE_DATE > E2.HIRE_DATE GROUP BY E.EMPLOYEE_ID;

-- g

SELECT E.EMPLOYEE_ID, COUNT(DISTINCT E2.EMPLOYEE_ID) EMPLOYEES_HIRED_BEFORE, COUNT(DISTINCT E3.EMPLOYEE_ID) EMPLOYEES_HIRED_AFTER FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON E.HIRE_DATE > E2.HIRE_DATE LEFT JOIN EMPLOYEES E3 ON E.HIRE_DATE < E3.HIRE_DATE GROUP BY E.EMPLOYEE_ID;

-- h

SELECT E.FIRST_NAME NAME FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON 
E.SALARY > E2.SALARY GROUP BY E.FIRST_NAME HAVING COUNT(E2.EMPLOYEE_ID) >=3;

-- i

SELECT E.LAST_NAME, (COUNT(DISTINCT E2.SALARY) + 1) RANK FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON E.SALARY < E2.SALARY GROUP BY E.LAST_NAME ORDER BY RANK; 

-- j

SELECT E.LAST_NAME, E.SALARY FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON E.SALARY < E2.SALARY GROUP BY E.EMPLOYEE_ID, E.LAST_NAME, E.SALARY HAVING COUNT(DISTINCT E2.EMPLOYEE_ID) < 3;

