--- 6.1

-- a

SELECT LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales');

-- b

SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales'));

-- c

SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales'));

-- d

SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE  ABS(SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales'))) <= 5000;

--- 6.2

-- a

SELECT LAST_NAME, SALARY FROM EMPLOYEES E WHERE 3<= (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E.EMPLOYEE_ID <> E2.EMPLOYEE_ID AND E.SALARY > E2.SALARY); 

-- b

SELECT D.DEPARTMENT_NAME, AVG(E.SALARY) AVG_SAL FROM DEPARTMENTS D JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID GROUP BY D.DEPARTMENT_NAME HAVING AVG(E.SALARY) > ANY
(SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID);

-- c

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) FROM DEPARTMENTS D JOIN EMPLOYEES E ON 
D.DEPARTMENT_ID = E.DEPARTMENT_ID GROUP BY D.DEPARTMENT_NAME HAVING COUNT(E.EMPLOYEE_ID) >= ALL (SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);  

-- d

SELECT LAST_NAME FROM EMPLOYEES E WHERE EXISTS (SELECT 1 FROM JOB_HISTORY WHERE EMPLOYEE_ID = E.EMPLOYEE_ID);

-- e

SELECT E.EMPLOYEE_ID, DS.MIN_SAL, DS.MAX_SAL FROM EMPLOYEES E JOIN (SELECT DEPARTMENT_ID, MIN(SALARY) MAX_SAL, MIN(SALARY) MIN_SAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID) DS ON E.DEPARTMENT_ID = DS.DEPARTMENT_ID;

-- f

SELECT J.JOB_TITLE, E.LAST_NAME FROM JOBS J JOIN (SELECT LAST_NAME, JOB_ID FROM EMPLOYEES WHERE (JOB_ID, SALARY) IN (SELECT JOB_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID)) E ON J.JOB_ID = E.JOB_ID;
