--- 8.2

-- a

UPDATE EMPLOYEES SET COMMISSION_PCT = 0 WHERE COMMISSION_PCT IS NULL;

-- b

UPDATE EMPLOYEES E SET SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES E2 WHERE E.DEPARTMENT_ID = E2.DEPARTMENT_ID);

-- c

UPDATE EMPLOYEES E SET COMMISSION_PCT = COMMISSION_PCT * (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.MANAGER_ID = E.EMPLOYEE_ID) WHERE (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.MANAGER_ID = E.EMPLOYEE_ID) > 0;

-- d

UPDATE EMPLOYEES SET HIRE_DATE = TO_DATE('01-01-' || TO_CHAR(HIRE_DATE, 'YYYY'), 'DD-MM-YYYY') WHERE TO_CHAR(HIRE_DATE, 'YYYY') < '2000';

--- 8.3

-- a

DELETE FROM EMPLOYEES WHERE SALARY < 5000;

-- b

DELETE FROM LOCATIONS L WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS D WHERE D.LOCATION_ID = L.LOCATION_ID);

-- c

DELETE FROM EMPLOYEES WHERE HIRE_DATE < TO_DATE('01-01-1997', 'DD-MM-YYYY'); 
