--- 2.1

-- a

SELECT DISTINCT COUNTRY_NAME FROM COUNTRIES;

-- b

SELECT DISTINCT JOB_TITLE FROM JOBS;

-- c

SELECT DISTINCT MANAGER_ID FROM EMPLOYEES;

-- d

SELECT DISTINCT CITY FROM LOCATIONS;

-- e

SELECT LOCATION_ID, STREET_ADDRESS, CITY,
STATE_PROVINCE, POSTAL_CODE FROM LOCATIONS;

--- 2.2

-- a

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES WHERE HIRE_DATE < TO_DATE('JAN-01-1998', 'MON-DD-YYYY');


-- b

SELECT LOCATION_ID, COUNTRY_NAME FROM LOCATIONS L LEFT JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID) WHERE COUNTRY_NAME = 'Canada' OR COUNTRY_NAME = 'Germany' OR COUNTRY_NAME = 'United Kingdom';

-- c

SELECT FIRST_NAME FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;

-- d

SELECT FIRST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE 'A%';

-- e

SELECT FIRST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE 'S%' AND LAST_NAME LIKE '%n';

-- f

SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE MANAGER_ID = 100;

-- g

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES WHERE JOB_ID = 'AD_PRES' AND SALARY >= 23000;

-- h

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES WHERE LOWER(LAST_NAME) NOT LIKE '%s%';

-- i

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT <= .3; 

-- j

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES WHERE HIRE_DATE > TO_DATE('JAN-01-1998', 'MON-DD-YYYY');

-- k

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1998';

--- 2.3

-- a

SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE JOB_ID = 'AD_PRES' 
ORDER BY COMMISSION_PCT ASC, SALARY DESC;

-- b

SELECT DISTINCT COUNTRY_NAME FROM COUNTRIES ORDER BY COUNTRY_NAME ASC;
